### ISSUE TITLE
[EventStore::Tiny 0.5] Warning: the following files are missing in your kit

### ISSUE THREAD

**Issue by twata1** [memowe/EventStore-Tiny#20]
Hi,

Running Strawberry Perl 5.14.4 32 bit, I noticed the following message.

`C:\home\heaven>cpan MEMOWE/EventStore-Tiny-0.5.tar.gz`

(snip)
```Checking if your kit is complete...  
Warning: the following files are missing in your kit:  
        EventStore-Tiny-0.41/META.json  
        EventStore-Tiny-0.41/META.yml  
Please inform the author.
```
(snip)

Thank you,

**Comment by memowe** [comment]
Hey @twata1, thanks for bringing this to my attention!

This seems a little weird to me as you're trying to install version 0.5, the process is looking at version 0.41 and in [both][v0.41] [distributions][v0.5] the `META` files are present.

Does anyone know what happens here?

[v0.41]: https://metacpan.org/source/MEMOWE/EventStore-Tiny-0.41
[v0.5]: https://metacpan.org/source/MEMOWE/EventStore-Tiny-0.5

**Comment by memowe** [comment]
Whoops, I was able to reproduce this warning. Seems somehow these files were found in my `MANIFEST` file. I fixed it. Thanks again! :heart: @twata1++

**Comment by memowe** [comment]
I created a new [dummy version](https://github.com/memowe/EventStore-Tiny/releases/tag/v0.51) with 4cd88ca to be able to distribute the correct version.

**Comment by memowe** [comment]
@twata1 - would you mind contacting me via [mail](mailto:mirko@westermeier.de)?

**Comment by twata1** [comment]
I sent mail.
